from sqlalchemy import URL, create_engine

from db_automation.config import Config


class DbConnector:
    """A basic connection to the database server.

    This class can be used to access the app's database server.

    Attributes
    ----------
    url : str
        string generated by SQL Alchemy's URL.create() method.
    engine
        callable engine for the database.
    """

    def __init__(self, db: str, *, echo=False) -> None:
        """
        Parameters
        ----------
        db
            the database to connect with.
        echo
            feedback from the database (default=False).
        """
        self.url = URL.create(
            "postgresql+psycopg",
            username=Config.DB_USERNAME,
            password=Config.DB_PASSWORD,
            host=Config.DB_HOST,
            port=Config.DB_PORT,
            database=db,
        )
        self.engine = create_engine(
            self.url,
            isolation_level="SERIALIZABLE",
            echo=echo
        )
